include_guard(DIRECTORY)

function     (make_imported_target)
  cmake_parse_arguments (PARSE_ARGV 0 "ARG" "" "TARGET_NAME" "INCLUDE_DIRS;LIBRARIES;DEBUG_LIBRARIES")
  if   (NOT "${ARG_UNPARSED_ARGUMENTS}" STREQUAL "")
    message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} was passed unexpected arguments: ${ARG_UNPARSED_ARGUMENTS}")
  endif()
  if   (NOT DEFINED "ARG_TARGET_NAME" OR "${ARG_TARGET_NAME}" STREQUAL "")
    message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} requires a TARGET_NAME argument.")
  endif()
  if   (DEFINED "ARG_DEBUG_LIBRARIES" AND NOT DEFINED "ARG_LIBRARIES")
    message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} requires a LIBRARIES argument when DEBUG_LIBRARIES is specified.")
  endif()

  add_library               ("${ARG_TARGET_NAME}" INTERFACE IMPORTED)
  target_include_directories("${ARG_TARGET_NAME}" INTERFACE ${ARG_INCLUDE_DIRS})
  if   (NOT DEFINED "ARG_DEBUG_LIBRARIES")
    target_link_libraries   ("${ARG_TARGET_NAME}" INTERFACE ${ARG_LIBRARIES})
  else ()
    target_link_libraries   ("${ARG_TARGET_NAME}" INTERFACE
      "$<$<CONFIG:Debug>:${ARG_DEBUG_LIBRARIES}>"
      "$<$<NOT:$<CONFIG:Debug>>:${ARG_LIBRARIES}>")
  endif()
endfunction  ()

function     (make_warnings_target)
  cmake_parse_arguments (PARSE_ARGV 0 "ARG" "" "TARGET_NAME" "")
  if   (NOT "${ARG_UNPARSED_ARGUMENTS}" STREQUAL "")
    message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} was passed unexpected arguments: ${ARG_UNPARSED_ARGUMENTS}")
  endif()
  if   (NOT DEFINED "ARG_TARGET_NAME" OR "${ARG_TARGET_NAME}" STREQUAL "")
    message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} requires a TARGET_NAME argument.")
  endif()

  string                (MD5 TARGET_HASH "${ARG_TARGET_NAME}")
  set                   (INTERNAL_TARGET_NAME "warnings_${TARGET_HASH}")
  add_library           ("${INTERNAL_TARGET_NAME}" INTERFACE)
  target_compile_options("${INTERNAL_TARGET_NAME}" INTERFACE
    "$<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CXX_COMPILER_FRONTEND_VARIANT:MSVC>>:/permissive-;/W4>"
    "$<$<AND:$<COMPILE_LANGUAGE:CXX>,$<NOT:$<CXX_COMPILER_FRONTEND_VARIANT:MSVC>>>:-Wall;-Wextra;-Wpedantic>")
  add_library           ("${ARG_TARGET_NAME}" ALIAS "${INTERNAL_TARGET_NAME}")
endfunction  ()

function     (get_cpm)
  cmake_parse_arguments (PARSE_ARGV 0 "ARG" "" "DESTINATION;VERSION;HASH" "")
  if   (NOT "${ARG_UNPARSED_ARGUMENTS}" STREQUAL "")
    message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} was passed unexpected arguments: ${ARG_UNPARSED_ARGUMENTS}")
  endif()
  if   (NOT DEFINED "ARG_DESTINATION" OR "${ARG_DESTINATION}" STREQUAL "")
    message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} requires a DESTINATION argument.")
  endif()
  if   (NOT DEFINED "ARG_VERSION" OR "${ARG_VERSION}" STREQUAL "")
    message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} requires a VERSION argument.")
  endif()
  if   (NOT DEFINED "ARG_HASH" OR "${ARG_HASH}" STREQUAL "")
    message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} requires a HASH argument.")
  endif()

  get_filename_component(CPM_DIRECTORY "${ARG_DESTINATION}" ABSOLUTE)
  set                   (CPM_FILE      "${CPM_DIRECTORY}/CPM_${ARG_VERSION}.cmake")
  if   (NOT EXISTS "${CPM_FILE}")
    file (MAKE_DIRECTORY "${CPM_DIRECTORY}")
    file (DOWNLOAD       "https://github.com/cpm-cmake/CPM.cmake/releases/download/v${ARG_VERSION}/CPM.cmake"
      "${CPM_FILE}" EXPECTED_HASH "SHA256=${ARG_HASH}")
  endif()
  include("${CPM_FILE}")
endfunction  ()

function     (make_cpack_source_ignore_files_from_gitignore)
  cmake_parse_arguments (PARSE_ARGV 0 "ARG" "" "GITIGNORE_PATH;OUTPUT_VARIABLE" "")
  if   (NOT "${ARG_UNPARSED_ARGUMENTS}" STREQUAL "")
    message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} was passed unexpected arguments: ${ARG_UNPARSED_ARGUMENTS}")
  endif()
  if   (NOT DEFINED "ARG_GITIGNORE_PATH" OR "${ARG_GITIGNORE_PATH}" STREQUAL "")
    message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} requires a GITIGNORE_PATH argument.")
  endif()
  if   (NOT DEFINED "ARG_OUTPUT_VARIABLE" OR "${ARG_OUTPUT_VARIABLE}" STREQUAL "")
    message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} requires an OUTPUT_VARIABLE argument.")
  endif()
  if   (NOT EXISTS "${ARG_GITIGNORE_PATH}")
    message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} requires an existing GITIGNORE_PATH: ${ARG_GITIGNORE_PATH}")
  endif()

  file  (STRINGS "${ARG_GITIGNORE_PATH}" GITIGNORE_LINES)
  set   (IGNORE_FILES)
  foreach(GITIGNORE_LINE IN LISTS GITIGNORE_LINES)
    string(STRIP "${GITIGNORE_LINE}" GITIGNORE_LINE)
    if   ("${GITIGNORE_LINE}" STREQUAL "" OR "${GITIGNORE_LINE}" MATCHES "^#")
      continue()
    endif()
    if   ("${GITIGNORE_LINE}" MATCHES "^!")
      message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} does not support negated gitignore patterns: ${GITIGNORE_LINE}")
    endif()
    if   ("${GITIGNORE_LINE}" MATCHES "\\*\\*")
      message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} does not support recursive gitignore patterns: ${GITIGNORE_LINE}")
    endif()

    set (PATTERN_IS_DIRECTORY FALSE)
    if  ("${GITIGNORE_LINE}" MATCHES "/$")
      set   (PATTERN_IS_DIRECTORY TRUE)
    endif()
    file  (TO_CMAKE_PATH "${GITIGNORE_LINE}" GITIGNORE_PATTERN)
    string(REGEX REPLACE "/$" "" GITIGNORE_PATTERN "${GITIGNORE_PATTERN}")
    if  ("${GITIGNORE_PATTERN}" MATCHES "^/")
      string(REGEX REPLACE "^/" "" GITIGNORE_PATTERN "${GITIGNORE_PATTERN}")
      set   (PATTERN_PREFIX "^/?")
    elseif("${GITIGNORE_PATTERN}" MATCHES "/")
      set   (PATTERN_PREFIX "^/?")
    else()
      set   (PATTERN_PREFIX "(^|.*/)")
    endif()

    string(REPLACE "."  "\\."    GITIGNORE_PATTERN_REGEX "${GITIGNORE_PATTERN}")
    string(REPLACE "+"  "\\+"    GITIGNORE_PATTERN_REGEX "${GITIGNORE_PATTERN_REGEX}")
    string(REPLACE "^"  "\\^"    GITIGNORE_PATTERN_REGEX "${GITIGNORE_PATTERN_REGEX}")
    string(REPLACE "$"  "\\$"    GITIGNORE_PATTERN_REGEX "${GITIGNORE_PATTERN_REGEX}")
    string(REPLACE "("  "\\("    GITIGNORE_PATTERN_REGEX "${GITIGNORE_PATTERN_REGEX}")
    string(REPLACE ")"  "\\)"    GITIGNORE_PATTERN_REGEX "${GITIGNORE_PATTERN_REGEX}")
    string(REPLACE "["  "\\["    GITIGNORE_PATTERN_REGEX "${GITIGNORE_PATTERN_REGEX}")
    string(REPLACE "]"  "\\]"    GITIGNORE_PATTERN_REGEX "${GITIGNORE_PATTERN_REGEX}")
    string(REPLACE "{"  "\\{"    GITIGNORE_PATTERN_REGEX "${GITIGNORE_PATTERN_REGEX}")
    string(REPLACE "}"  "\\}"    GITIGNORE_PATTERN_REGEX "${GITIGNORE_PATTERN_REGEX}")
    string(REPLACE "|"  "\\|"    GITIGNORE_PATTERN_REGEX "${GITIGNORE_PATTERN_REGEX}")
    string(REPLACE "?"  "[^/]"   GITIGNORE_PATTERN_REGEX "${GITIGNORE_PATTERN_REGEX}")
    string(REPLACE "*"  "[^/]*"  GITIGNORE_PATTERN_REGEX "${GITIGNORE_PATTERN_REGEX}")

    if   (PATTERN_IS_DIRECTORY)
      set   (IGNORE_PATTERN "${PATTERN_PREFIX}${GITIGNORE_PATTERN_REGEX}(/.*)?$")
    else()
      set   (IGNORE_PATTERN "${PATTERN_PREFIX}${GITIGNORE_PATTERN_REGEX}$")
    endif()
    string(REPLACE "\\" "\\\\" IGNORE_PATTERN "${IGNORE_PATTERN}")
    list  (APPEND IGNORE_FILES "${IGNORE_PATTERN}")
  endforeach()

  set("${ARG_OUTPUT_VARIABLE}" ${IGNORE_FILES} PARENT_SCOPE)
endfunction  ()
