include_guard(DIRECTORY)

function     (make_imported_target)
  cmake_parse_arguments (PARSE_ARGV 0 "ARG" "" "TARGET_NAME" "INCLUDE_DIRS;LIBRARIES;DEBUG_LIBRARIES")
  if   (NOT "${ARG_UNPARSED_ARGUMENTS}" STREQUAL "")
    message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} was passed unexpected arguments: ${ARG_UNPARSED_ARGUMENTS}")
  endif()
  if   (NOT DEFINED "ARG_TARGET_NAME" OR "${ARG_TARGET_NAME}" STREQUAL "")
    message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} requires a TARGET_NAME argument.")
  endif()
  if   (DEFINED "ARG_DEBUG_LIBRARIES" AND NOT DEFINED "ARG_LIBRARIES")
    message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} requires a LIBRARIES argument when DEBUG_LIBRARIES is specified.")
  endif()

  add_library               ("${ARG_TARGET_NAME}" INTERFACE IMPORTED)
  target_include_directories("${ARG_TARGET_NAME}" INTERFACE ${ARG_INCLUDE_DIRS})
  if   (NOT DEFINED "ARG_DEBUG_LIBRARIES")
    target_link_libraries   ("${ARG_TARGET_NAME}" INTERFACE ${ARG_LIBRARIES})
  else ()
    target_link_libraries   ("${ARG_TARGET_NAME}" INTERFACE
      "$<$<CONFIG:Debug>:${ARG_DEBUG_LIBRARIES}>"
      "$<$<NOT:$<CONFIG:Debug>>:${ARG_LIBRARIES}>")
  endif()
endfunction  ()

function     (make_warnings_target)
  cmake_parse_arguments (PARSE_ARGV 0 "ARG" "" "TARGET_NAME" "")
  if   (NOT "${ARG_UNPARSED_ARGUMENTS}" STREQUAL "")
    message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} was passed unexpected arguments: ${ARG_UNPARSED_ARGUMENTS}")
  endif()
  if   (NOT DEFINED "ARG_TARGET_NAME" OR "${ARG_TARGET_NAME}" STREQUAL "")
    message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} requires a TARGET_NAME argument.")
  endif()

  string                (MD5 TARGET_HASH "${ARG_TARGET_NAME}")
  set                   (INTERNAL_TARGET_NAME "warnings_${TARGET_HASH}")
  add_library           ("${INTERNAL_TARGET_NAME}" INTERFACE)
  target_compile_options("${INTERNAL_TARGET_NAME}" INTERFACE
    "$<$<AND:$<COMPILE_LANGUAGE:CXX>,$<CXX_COMPILER_FRONTEND_VARIANT:MSVC>>:/permissive-;/W4>"
    "$<$<AND:$<COMPILE_LANGUAGE:CXX>,$<NOT:$<CXX_COMPILER_FRONTEND_VARIANT:MSVC>>>:-Wall;-Wextra;-Wpedantic>")
  add_library           ("${ARG_TARGET_NAME}" ALIAS "${INTERNAL_TARGET_NAME}")
endfunction  ()

function     (add_package_dependency)
  if   (ARGC EQUAL 0)
    message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} requires at least one argument.")
  endif()

  string(REPLACE ";" " " PACKAGE_ARGUMENTS "${ARGV}")
  set   (PACKAGE_DEPENDENCIES "${PACKAGE_DEPENDENCIES}find_dependency(${PACKAGE_ARGUMENTS})\n" PARENT_SCOPE)
endfunction  ()

function     (prepare_vcpkg)
  cmake_parse_arguments (PARSE_ARGV 0 "ARG" "" "VERSION" "")
  if   (NOT "${ARG_UNPARSED_ARGUMENTS}" STREQUAL "")
    message(FATAL_ERROR "The ${CMAKE_CURRENT_FUNCTION} was passed unexpected arguments: ${ARG_UNPARSED_ARGUMENTS}")
  endif()

  if   (NOT DEFINED VCPKG_ROOT OR "${VCPKG_ROOT}" STREQUAL "")
    set(VCPKG_ROOT "${CMAKE_SOURCE_DIR}/build/vcpkg")
  endif()
  set  (VCPKG_ROOT "${VCPKG_ROOT}" CACHE PATH "VCPKG root directory.")

  if   (NOT DEFINED VCPKG_INSTALLED_DIR OR "${VCPKG_INSTALLED_DIR}" STREQUAL "")
    set(VCPKG_INSTALLED_DIR "${CMAKE_SOURCE_DIR}/build/vcpkg_installed")
  endif()
  set  (VCPKG_INSTALLED_DIR "${VCPKG_INSTALLED_DIR}" CACHE PATH "VCPKG installed directory.")

  if   (NOT EXISTS "${VCPKG_ROOT}/.git")
    file           (MAKE_DIRECTORY "${VCPKG_ROOT}")
    execute_process(COMMAND git clone https://github.com/Microsoft/vcpkg.git "${VCPKG_ROOT}" RESULT_VARIABLE RETURN_CODE)
    if   (NOT RETURN_CODE EQUAL 0)
      message(FATAL_ERROR "Failed to clone VCPKG.")
    endif()
  endif()

  if   (DEFINED ARG_VERSION AND NOT "${ARG_VERSION}" STREQUAL "")
    execute_process(COMMAND git -C "${VCPKG_ROOT}" checkout "${ARG_VERSION}" RESULT_VARIABLE RETURN_CODE)
    if   (NOT RETURN_CODE EQUAL 0)
      message(FATAL_ERROR "Failed to checkout VCPKG version ${ARG_VERSION}.")
    endif()
  endif()

  if   (CMAKE_HOST_WIN32 AND NOT MSYS AND NOT CYGWIN)
    set(VCPKG_BOOTSTRAP  "${VCPKG_ROOT}/bootstrap-vcpkg.bat")
    set(VCPKG_EXECUTABLE "${VCPKG_ROOT}/vcpkg.exe")
  else ()
    set(VCPKG_BOOTSTRAP  "${VCPKG_ROOT}/bootstrap-vcpkg.sh")
    set(VCPKG_EXECUTABLE "${VCPKG_ROOT}/vcpkg")
  endif()

  if   (NOT EXISTS "${VCPKG_EXECUTABLE}")
    execute_process(COMMAND "${VCPKG_BOOTSTRAP}" -disableMetrics WORKING_DIRECTORY "${VCPKG_ROOT}" RESULT_VARIABLE RETURN_CODE)
    if   (NOT RETURN_CODE EQUAL 0)
      message(FATAL_ERROR "Failed to bootstrap VCPKG.")
    endif()
  endif()

  set(CMAKE_TOOLCHAIN_FILE "${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" CACHE FILEPATH "VCPKG toolchain file.")
endfunction  ()
